### ISSUE TITLE
SVELTE: createMethod should never be called on the client. Ensure you have @zodern/babel-plugin-meteor-reify configured

### ISSUE THREAD

**Issue by tosinek** [zodern/meteor-relay#11]
I think I follow the steps as per readme, but it doesn't seem to be working. Maybe the babel plugin doesn't work here?
Also the error message references meteor-reify, which is nowhere to be found, so I guess it is just a typo in the `client-main.ts` file.

An example repo https://github.com/tosinek/zodern-relay-error
It is just the `meteor create --svelte` with `zodern-relay` added.

**Comment by lakyadam** [comment]
Same issue for react project. I think zodern:relay is not maintained anymore unfortunately :(

**Comment by tosinek** [comment]
Yes, Windows. I've just tried to run it in WSL and it works fine (after adding a schema to the method).

**Comment by zodern** [comment]
I released an update to the babel plugin that fixes running on Windows.

**Comment by tosinek** [comment]
You are the best, thank you zodern! (I am loggin another bug though :))
