### ISSUE TITLE
Type definitions are using wrong slash on Windows

### ISSUE THREAD

**Issue by tosinek** [zodern/meteor-relay#12]
In `.meteor/local/types/packages.d.ts` the entries for your packages (in my case namely relay and montiapm, there are wrong (back)slashes on Windows

```
declare module 'meteor/zodern:relay' {
  import exports = require('package-types/zodern_relay/package/web.cordova\__types\server-main.d')
                                                                          ^       ^
  export = exports
}
declare module 'meteor/montiapm:agent' {
  import exports = require('package-types/montiapm_agent/package/web.cordova\types.d')
  export = exports
}
```

After manually fixing it (on every server restart!), everything works like a charm. It looks like removing zodern:types after everything is initially set up is a feasible **workaround**.

A side note:
There is only one public repo with zodern:relay as an example. I tried to run it (and also my project) in WSL but got a similar slash-related issue in VS Code on Windows (so the typings didn't work), but that might be just my incorrect env setup (maybe missing some VS Code WSL plugins to interpred slashes correctly).

**Comment by zodern** [comment]
Thanks for creating the issue. I published a new version of zodern:types that fixes this.
