### ISSUE TITLE
how to use export default of method?

### ISSUE THREAD

**Issue by welkinwong** [zodern/meteor-relay#19]
thanks for your great package 👍👍👍

I want to use export default, like:

```ts
const myMethod = createMethod({
  name: 'myMethod',
  schema,
  run() {}
});

export default myMethod
```

but this code return `undefined` in client side ( server side is correct )

PS: I used to one method in one file

**Comment by zodern** [comment]
Hi. Default exports are currently not supported. The babel plugin removes all code except exports for methods and publications, and figuring out if that applies to the default export would be more complicated. If would be open to accepting a PR that implements it.

**Comment by welkinwong** [comment]
I try change babel plugin, but fail
the problem unimportance, so close this
