### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by generalleger** [zodern/meteor-relay#3]
I am not sure if this is intended behavior, or if I am doing something wrong.

Details below are based on a Meteor 2.9 app created with `meteor create --typescript` flag and following the 3 Getting Started steps in the docs and the 'add' method example.

/imports/methods/add.ts

```
import { createMethod } from 'meteor/zodern:relay';
import { z } from 'zod';

export const add = createMethod({
  name: 'add',
  schema: z.number().array().length(2),
  run([a, b]) {
    return a + b;
  },
});
```

/client/main.tsx

```
...default code from meteor create

add([1, 2]).then(result => {
  console.log(result) // logs 3
});
```
I am getting a Method not found error in the browser.

```
details : undefined
error: 404
errorType: "Meteor.Error"
isClientSafe: true
message: "Method 'add' not found [404]"
reason: "Method 'add' not found"
stack: "Error: Method 'add' not found [404]
```

The error goes away if I import the method on the server and do something with the import
/server/main.ts

```
import { add } from '/imports/methods/add'

typeof add;
```

**Comment by zodern** [comment]
You do need to import the method or publication files on the server. You can simply do `import '/imports/methods/add`.
This probably should be mentioned in the docs.

I tend to forget to add these imports, so I'm considering adding an option to the babel plugin to have it automatically add them someplace.

**Comment by generalleger** [comment]
+1 for the babel plugin idea

Thank you kindly for the fast response, and for the very cool library.

**Comment by banjerluke** [comment]
For anyone seeing this in the future and to save them some time, one can run the following command in the `methods` or `publications` directories that need importing on the server:

```js
find . -type f | grep -v './index' | sed "s/^./import from '/" | sed "s/\.ts/'/"
```

This will give you `import` statements for all the files in all subdirectories, except for the `./index.(js|ts)` file, which is where I paste/pipe the results of this command. Then I can just import e.g. `/imports/methods` from my server startup code and I'm good to go. We'll see how effective I am at remembering to do this the next time I go to add a method or publication. 🤣
